### ISSUE TITLE
Example in README.md is broken

### ISSUE THREAD

**Issue by cosletmihai** [zbw/sparql-gui-gh#2]
This example on the README page uses [http://data.nobelprize.org/sparql](http://data.nobelprize.org/sparql) as its data source:

> Example: The URL
> http://zbw.eu/beta/sparql-lab/?queryRef=https://api.github.com/repos/zbw/sparql-queries/contents/class_overview.rq&endpoint=http://data.nobelprize.org/sparql

which doesn't seem to contain the data anymore, giving a 
```
Error 404: Service Description: /nobel/query

Fuseki - version 1.1.0 (Build date: 2014-07-26T18:10:29+0100)
```
when accessed.

**Comment by jneubert** [comment]
Well - their Fuseki is still alive, but is not answering the most simple queries. Perhaps it will be fixed soon, otherwise I will have to look for another not-so-large example dataset.

Thank you for bringing this up!

**Comment by jneubert** [comment]
Problem seems to be, that browsers are much more strictly checking CORS rules. What we get (in Firefo) is:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://data.nobelprize.org/sparql. (Reason: CORS request did not succeed) [[Learn More](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed)]

I suppose we cannot do much on our side - just exchanged the link with a working example.

**Comment by cosletmihai** [comment]
awesome, thank you!
